///////////////////////////////////////ADMIN//////////////////////////////////////
export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';
export const ADMIN_USER_LIST_RESET = 'ADMIN_USER_LIST_RESET';

export const ADMIN_DR_LIST_REQUEST = 'ADMIN_DR_LIST_REQUEST';
export const ADMIN_DR_LIST_SUCCESS = 'ADMIN_DR_LIST_SUCCESS';
export const ADMIN_DR_LIST_FAIL = 'ADMIN_DR_LIST_FAIL';
export const ADMIN_DR_LIST_RESET = 'ADMIN_DR_LIST_RESET';

export const ADMIN_RDV_LIST_REQUEST = 'ADMIN_RDV_LIST_REQUEST';
export const ADMIN_RDV_LIST_SUCCESS = 'ADMIN_RDV_LIST_SUCCESS';
export const ADMIN_RDV_LIST_FAIL = 'ADMIN_RDV_LIST_FAIL';
export const ADMIN_RDV_LIST_RESET = 'ADMIN_RDV_LIST_RESET';

export const ADMIN_PAYMENT_LIST_REQUEST = 'ADMIN_PAYMENT_LIST_REQUEST';
export const ADMIN_PAYMENT_LIST_SUCCESS = 'ADMIN_PAYMENT_LIST_SUCCESS';
export const ADMIN_PAYMENT_LIST_FAIL = 'ADMIN_PAYMENT_LIST_FAIL';
export const ADMIN_PAYMENT_LIST_RESET = 'ADMIN_PAYMENT_LIST_RESET';