export const RDV_CREATE_REQUEST = 'RDV_CREATE_REQUEST';
export const RDV_CREATE_SUCCESS = 'RDV_CREATE_SUCCESS';
export const RDV_CREATE_FAIL = 'RDV_CREATE_FAIL';

export const RDV_DETAILS_REQUEST = 'RDV_DETAILS_REQUEST';
export const RDV_DETAILS_SUCCESS = 'RDV_DETAILS_SUCCESS';
export const RDV_DETAILS_FAIL = 'RDV_DETAILS_FAIL';

export const RDV_PAY_REQUEST = 'RDV_PAY_REQUEST';
export const RDV_PAY_SUCCESS = 'RDV_PAY_SUCCESS';
export const RDV_PAY_FAIL = 'RDV_PAY_FAIL';
export const RDV_PAY_RESET = 'RDV_PAY_RESET';

export const RDV_PATIENT_LIST_REQUEST = 'RDV_PATIENT_LIST_REQUEST';
export const RDV_PATIENT_LIST_SUCCESS = 'RDV_PATIENT_LIST_SUCCESS';
export const RDV_PATIENT_LIST_FAIL = 'RDV_PATIENT_LIST_FAIL';
export const RDV_PATIENT_LIST_RESET = 'RDV_PATIENT_LIST_RESET';

export const RDV_DOCTOR_LIST_REQUEST = 'RDV_DOCTOR_LIST_REQUEST';
export const RDV_DOCTOR_LIST_SUCCESS = 'RDV_DOCTOR_LIST_SUCCESS';
export const RDV_DOCTOR_LIST_FAIL = 'RDV_DOCTOR_LIST_FAIL';
export const RDV_DOCTOR_LIST_RESET = 'RDV_DOCTOR_LIST_RESET';

export const RDV_DELIVER_REQUEST = 'RDV_DELIVER_REQUEST';
export const RDV_DELIVER_SUCCESS = 'RDV_DELIVER_SUCCESS';
export const RDV_DELIVER_FAIL = 'RDV_DELIVER_FAIL';
export const RDV_DELIVER_RESET = 'RDV_DELIVER_RESET';

export const RDV_DELETE_REQUEST = 'RDV_DELETE_REQUEST';
export const RDV_DELETE_SUCCESS = 'RDV_DELETE_SUCCESS';
export const RDV_DELETE_FAIL = 'RDV_DELETE_FAIL';
